---
# Per environment values which override defaults in hmpps-trivy-discovery/values.yaml

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod

discoveryCronJob:
  env:
    LOG_LEVEL: debug
  namespace_secrets:
    hmpps-trivy-discovery:
      SC_FILTER: "SC_FILTER"
