---
# Per environment values which override defaults in hmpps-trivy-discovery/values.yaml

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-prod

discoveryCronJob:
  env:
    REFRESH_INTERVAL: "180"
    REDIS_MAX_STREAM_LENGTH: 1440
    LOG_LEVEL: info