---
# Per environment values which override defaults in hmpps-trivy-discovery/values.yaml

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod

discoveryCronJob:
  enabled: true
  full_scan_schedule: "15 13 * * 1"
  incremental_scan_schedule: "00 8 * * 1-5"
  env:
    REDIS_MAX_STREAM_LENGTH: 360
    LOG_LEVEL: debug
  namespace_secrets:
    hmpps-trivy-discovery:
      SC_FILTER: "SC_FILTER"
