---
# Per environment values which override defaults in hmpps-trivy-discovery/values.yaml

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-prod

discoveryCronJob:
  env:
    LOG_LEVEL: info