---

generic-prometheus-alerts:
  targetApplication: hmpps-trivy-discovery

discoveryCronJob:
  enabled: true
  image:
    repository: ghcr.io/ministryofjustice/hmpps-trivy-discovery
    port: 8080
  namespace_secrets:
    hmpps-trivy-discovery:
      SERVICE_CATALOGUE_API_ENDPOINT: "SERVICE_CATALOGUE_API_ENDPOINT"
      SERVICE_CATALOGUE_API_KEY: "SERVICE_CATALOGUE_API_KEY"
      SLACK_BOT_TOKEN: "SLACK_BOT_TOKEN"
